1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int)
print(a)

[0 1 2 3 4 5 6 7 8 9]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
b = np.zeros((3, 3), dtype=int)
print(b)

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
c = np.random.randint(1, 11, size=(5, 5))
print(c)

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
d = np.random.random((4, 4))
print(d)

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
e = np.random.randint(1, 10, size=(5,))
f = np.random.randint(1, 10, size=(5,))
print(e, f)
print(e + f)
print(e - f)
print(e * f)
print(e / f)

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
g = np.random.rand(7)
h = np.random.rand(7)
gh = np.dot(g, h)
print(g, h, sep='\n')
print(gh)

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
i = np.random.randint(1, 11, (2, 2), dtype=int)
j = np.random.randint(1, 11, (2, 3), dtype=int)
print(i)
print(j)
print(np.dot(i, j))


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
k = np.random.randint(1, 11, (3,3))
k_inv =np.linalg.inv(k)
print(k)
print(k_inv)

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
l = np.random.random((4, 4))
l_transp = l.T
print(l)
print(l_transp) 

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
m = np.random.randint(1, 11, size=(3, 4))
n =np.random.randint(1, 11, 4)

print(m)
print(n)
print(np.dot(m,n))

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
o = np.random.random((2,3))
p =np.random.random(3)

print(o)
print(p)
print(np.dot(o,p))

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
q = np.random.randint(1, 11, (2, 2))
r = np.random.randint(1, 11, (2, 2))
qr = np.multiply(q, r)
print(q, r, qr, sep='\n')

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
s = np.random.randint(1, 11, (2, 2))
t = np.random.randint(1, 11, (2, 2))
st = np.dot(s, t)
print(s, t, st, sep='\n')

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
u = np.random.randint(1, 101, (5, 5))
print(u, u.sum(), sep='\n')

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
v1 = np.random.randint(1, 11, (4, 4))
v2 = np.random.randint(1, 11, (4, 4))
v1_sub_v2 = np.subtract(v1, v2)
print(v1, v2, v1-v2, v1_sub_v2, sep='\n')

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
x = np.random.random((3, 3))
x_vector = np.array([el.sum() for el in x])
print(x)
print(x_vector)
# або так:
row_sums_vector = np.sum(x, axis=1, keepdims=True)
print(row_sums_vector)

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел. 

In [ ]:
y = np.random.randint(1, 1001, (3, 4))
y_sqr = np.square(y)
print(y, y_sqr, sep='\n')


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [3]:
z = np.random.randint(1, 51, size=4)
z_sqrt = np.sqrt(z)
print(z, z_sqrt, sep='\n')

[5 9 7 8]
[2.23606798 3.         2.64575131 2.82842712]
